package com.example.compilador;

public enum Tokens {
    YEAH_BUDDY,  LIGHT, WEIGHT, BABY, YUP, UUUU,
    SHOW_ME_THAT, SECOND,

    // Tipos de token
    IDENTIFICADOR, NUMERO, CADENA, BOOLEANO, CARACTER,
    SUMA, RESTA, MULTIPLICACION, DIVISION, ASIGNACION, COMA, PUNTO_Y_COMA, PARENTESIS_IZQ, PARENTESIS_DER,COMILLADOBLE, COMILLASIMPLE,
    DIAGONAL,

    // Fin de archivo / error
    SKINNY_B, ERROR
}
